In [3]:
from bag_of_words import bag_words

sentences_arab=['أنا أحب تعلم الآلة', 'تعلم الآلة ممتع', 'أنا أحب التعلم']

sentences = ["Machine learning is awesome",
             "NLP is the future!",
             "The children are our future",
             "Our children's children are our grandchildren",
             "The cake was not very good",
             "No one said that the cake was not very good",
             "Life is kl"]
bags, features = bag_words(sentences_arab)
print(bags.toarray(), features)


[[1 1 1 0 1 0]
 [0 0 1 0 1 1]
 [1 1 0 1 0 0]] ['أحب' 'أنا' 'الآلة' 'التعلم' 'تعلم' 'ممتع']


In [6]:
from TF_IDF import TF_IDf
sentences = ["Machine learning is awesome",
             "NLP is the future!",
             "The children are our future",
             "Our children's children are our grandchildren",
             "The cake was not very good",
             "No one said that the cake was not very good",
             "Life is beautiful"]
vocab = ["awesome", "learning", "children", "cake", "good", "none", "machine"]
E, F = TF_IDf(sentences, vocab)
print(E.toarray())
print(F)

[[0.57735027 0.57735027 0.         0.         0.         0.
  0.57735027]
 [0.         0.         0.         0.         0.         0.
  0.        ]
 [0.         0.         1.         0.         0.         0.
  0.        ]
 [0.         0.         1.         0.         0.         0.
  0.        ]
 [0.         0.         0.         0.70710678 0.70710678 0.
  0.        ]
 [0.         0.         0.         0.70710678 0.70710678 0.
  0.        ]
 [0.         0.         0.         0.         0.         0.
  0.        ]]
['awesome' 'learning' 'children' 'cake' 'good' 'none' 'machine']


In [1]:
from word2vector import word_to_vector


2025-09-07 23:21:20.341215: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
2025-09-07 23:21:20.568485: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2025-09-07 23:21:24.847240: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.


In [2]:
model, word2idx = word_to_vector()
print(word2idx)

/home/ahmed/anaconda3/lib/python3.13/site-packages/keras/src/layers/core/embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(
2025-09-07 23:21:29.961640: E external/local_xla/xla/stream_executor/cuda/cuda_platform.cc:51] failed call to cuInit: INTERNAL: CUDA error: Failed call to cuInit: UNKNOWN ERROR (303)


Epoch 1/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 2s 75ms/step - accuracy: 0.1364 - loss: 2.0751
Epoch 2/100
1/2 ━━━━━━━━━━━━━━━━━━━━ 0s 188ms/step - accuracy: 0.2188 - loss: 2.0742

/home/ahmed/anaconda3/lib/python3.13/site-packages/keras/src/callbacks/early_stopping.py:99: UserWarning: Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: accuracy,loss
  current = self.get_monitor_value(logs)


2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 74ms/step - accuracy: 0.2045 - loss: 2.0721 
Epoch 3/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 75ms/step - accuracy: 0.2727 - loss: 2.0692
Epoch 4/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 75ms/step - accuracy: 0.2727 - loss: 2.0665
Epoch 5/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 241ms/step - accuracy: 0.2727 - loss: 2.0640
Epoch 6/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 72ms/step - accuracy: 0.2727 - loss: 2.0614 
Epoch 7/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 71ms/step - accuracy: 0.2955 - loss: 2.0587 
Epoch 8/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step - accuracy: 0.2955 - loss: 2.0563
Epoch 9/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 91ms/step - accuracy: 0.3409 - loss: 2.0538 
Epoch 10/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 70ms/step - accuracy: 0.3636 - loss: 2.0512
Epoch 11/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 79ms/step - accuracy: 0.3636 - loss: 2.0489 
Epoch 12/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 79ms/step - accuracy: 0.3636 - loss: 2.0462 
Epoch 13/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 125ms/step - accuracy: 0.3409 - loss

In [3]:
idx2word = {i:word for word, i in word2idx.items()}
print(idx2word)

{0: 'a', 1: 'woman,', 2: 'she', 3: 'is', 4: 'king,', 5: 'man,', 6: 'queen,', 7: 'he'}


In [12]:
import numpy as np
probs = model.predict(np.array([word2idx['she']]))
print(idx2word[np.argmax(probs)])


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 90ms/step
is


In [3]:
embeddings = model.layers[1].get_weights()[0]  # مصفوفة embeddings
word_vector = embeddings[0]  # vector للكلمة رقم 0
print(word_vector)


[-0.17411861 -0.12506168 -0.01964044 -0.00620237  0.03283032 -0.08119701
  0.15395787 -0.10846621  0.1150386   0.20014834]
