In [1]:
import numpy as np


# Simulate data
num_samples = 10
num_classes = 3

# True labels (as integers)
true_classes = np.random.randint(0, num_classes, size=num_samples)

# Predicted classes (simulated predictions)
predicted_classes = np.random.randint(0, num_classes, size=num_samples)

# Convert to one-hot
labels = np.eye(num_classes)[true_classes]
logits = np.eye(num_classes)[predicted_classes]

# Save to .npz
np.savez('labels_logits.npz', labels=labels, logits=logits)

print("labels_logits.npz file created.")

labels_logits.npz file created.


In [1]:
from confusion_matrix import confusion_matraix
import numpy as np


if __name__ == '__main__':
    lib = np.load('labels_logits.npz')
    labels = lib['labels']
    logits = lib['logits']

    np.set_printoptions(suppress=True)
    confusion = confusion_matraix(labels, logits)
    print(confusion)
    np.savez_compressed('confusion.npz', confusion=confusion)

[[1. 0. 0.]
 [1. 1. 1.]
 [1. 1. 4.]]


In [3]:
labels = np.array([
    [1, 0, 0],  # true = class 0
    [0, 1, 0],  # true = class 1
    [0, 1, 0],  # true = class 1
    [0, 0, 1],  # true = class 2
])

logits = np.array([
    [1, 0, 0],  # predicted = class 0 ✅
    [0, 1, 0],  # predicted = class 1 ✅
    [1, 0, 0],  # predicted = class 0 ❌
    [0, 0, 1],  # predicted = class 2 ✅
])
print(confusion_matraix(labels, logits))

[[1 0 0]
 [1 1 0]
 [0 0 1]]
