In [ ]:
import tensorflow.keras as tf


2025-06-30 21:02:15.169249: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
E0000 00:00:1751306535.220198    7508 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1751306535.233310    7508 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1751306535.269196    7508 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1751306535.269231    7508 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1751306535.269235    7508 computation_placer.cc:177] computation placer alr

In [4]:
#0. Sequential
def build_model(nx, layers, activations, lambath, keep_prop):
    model = tf.Sequential()
    l2 = tf.regularizers.L2(lambath)
    for i in range(len(layers)):
        if i == 0:
            model.add(tf.layers.Dense(layers[i], activation=activations[i], 
                                    kernel_regularizer=l2, input_shape=(nx, )))
        else:
            model.add(tf.layers.Dense(layers[i], activation=activations[i],kernel_regularizer=l2
                                      ))
        if i < len(layers) -1:
            model.add(tf.layers.Dropout(1 - keep_prop))
    return model


In [9]:
network = build_model(784, [256, 256, 10], ['tanh', 'tanh', 'softmax'], 0.001, .95)
network.summary()
print(network.losses)

/home/ahmed/venv/lib/python3.12/site-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Model: "sequential_5"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_13 (Dense)                │ (None, 256)            │       200,960 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_9 (Dropout)             │ (None, 256)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_14 (Dense)                │ (None, 256)            │        65,792 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_10 (Dropout)            │ (None, 256)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_15 (Dense)                │ (None, 10)             │         2,570 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 269,322 (1.03 MB)

 Trainable params: 269,322 (1.03 MB)

 Non-trainable params: 0 (0.00 B)

[<tf.Tensor: shape=(), dtype=float32, numpy=0.3860100507736206>, <tf.Tensor: shape=(), dtype=float32, numpy=0.25464001297950745>, <tf.Tensor: shape=(), dtype=float32, numpy=0.019573908299207687>]


In [ ]:
#optimizer
import tensorflow.keras as tf
def optimzer_model(network, alpha, beta1, beta2):
    opt = tf.optimizers.Adam(learning_rate=alpha, beta_1=beta1, beta_2=beta2)
    network.compile(optimizer=opt, loss=['categorical_crossentropy'], metrics=['accuracy'])
    

In [12]:
#one_hot
def one_hot(labels, classess=None):
    return tf.utils.to_categorical(labels, classess)

In [14]:
labels = [1 , 2, 0]
labels = one_hot(labels)
print(labels)

[[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]


In [23]:
#train
def train_model(network, data, labels, batch_size, verbose, epochs):
    trained_model = network.fit(x=data, y=labels, batch_size=batch_size, verbose=verbose, shuffle=True, epochs=epochs)
    return trained_model

In [ ]:
import numpy as np

data = [
    [1, 2, 3, 4, 5],
    [5, 4, 3, 2, 1],
    [2, 3, 4, 5, 6],
    [0, 1, 2, 3, 4],
    [9, 8, 7, 6, 5]
]
labels = [4, 6, 10, 14, 12]

data = np.array(data)
labels = np.array(labels)
network = build_model(5, [5, 300, 500], ['tanh', 'tanh', 'tanh'], .001, .95)
optimzer_model(network, .001, .9, .999)
train_model(network, data, labels, batch_size=2, verbose=1, epochs= 12)

Epoch 1/12
3/3 ━━━━━━━━━━━━━━━━━━━━ 5s 48ms/step - accuracy: 0.0000e+00 - loss: 19.7888
Epoch 2/12
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.0000e+00 - loss: 18.9740 
Epoch 3/12
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step - accuracy: 0.0000e+00 - loss: 17.8818 
Epoch 4/12
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 89ms/step - accuracy: 0.0000e+00 - loss: 10.6121
Epoch 5/12
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step - accuracy: 0.0000e+00 - loss: 10.6244
Epoch 6/12
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.2875 - loss: 8.5334 
Epoch 7/12
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 0.4500 - loss: 8.1238
Epoch 8/12
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step - accuracy: 0.5750 - loss: 7.2843 
Epoch 9/12
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.4500 - loss: 6.7470 
Epoch 10/12
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.2625 - loss: 10.7676     
Epoch 11/12
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 78ms/step - accuracy: 0.3250 - loss: 9.4688     
Epoch 12/12
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 77ms

In [ ]:
import tensorflow.keras as k
import numpy as np
x = np.array([4, 10, 5, 3, 1], dtype=float)
y = np.array([8, 20, 10, 6, 2], dtype=float)
l2 = k.regularizers.L2
model = k.Sequential([
    k.layers.Dense(units=1, input_shape=[1])
])
model.summary()
opt= k.optimizers.SGD()
early_stoping = k.callbacks.EarlyStopping(
    monitor='val_loss',
    patience=15,

)
model.compile(optimizer=opt, loss='mean_squared_error')
model.fit(x=x, y=y, epochs=50 , validation_split=.1, callbacks=early_stoping)

/home/ahmed/venv/lib/python3.12/site-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Model: "sequential_16"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_26 (Dense)                │ (None, 1)              │             2 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2 (8.00 B)

 Trainable params: 2 (8.00 B)

 Non-trainable params: 0 (0.00 B)

Epoch 1/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step - loss: 19.2726 - val_loss: 0.0101
Epoch 2/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 485ms/step - loss: 1.0553 - val_loss: 0.0019
Epoch 3/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 262ms/step - loss: 0.0596 - val_loss: 0.0059
Epoch 4/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 233ms/step - loss: 0.0052 - val_loss: 0.0071
Epoch 5/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 322ms/step - loss: 0.0022 - val_loss: 0.0074
Epoch 6/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 325ms/step - loss: 0.0020 - val_loss: 0.0074
Epoch 7/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 309ms/step - loss: 0.0020 - val_loss: 0.0074
Epoch 8/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 275ms/step - loss: 0.0020 - val_loss: 0.0073
Epoch 9/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 374ms/step - loss: 0.0019 - val_loss: 0.0073
Epoch 10/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 250ms/step - loss: 0.0019 - val_loss: 0.0072
Epoch 11/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 251ms/step - loss: 0.0019 - val_loss: 0.0072
Epoch 12/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 285ms/step - loss: 0.0019 - val_loss

In [35]:
model.predict(np.array([12]))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 287ms/step


array([[23.925434]], dtype=float32)

In [37]:
model.save('my_model.h5')

In [46]:
new_model = k.models.load_model('my_model.h5')

In [49]:
new_model.predict(np.array([5]))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 470ms/step


array([[10.025499]], dtype=float32)

In [41]:
model_json = model.to_json()
with open('model_json', 'w') as f:
    f.write(model_json)


In [45]:
model.save_weights('mymodel.weights.h5')

In [51]:

with open('model_json', 'r') as f:
    new_model2 = k.models.model_from_json(f.read())
new_model2.load_weights('mymodel.weights.h5')
new_model2.compile('sgd', loss='mean_squared_error')

/home/ahmed/venv/lib/python3.12/site-packages/keras/src/saving/saving_lib.py:802: UserWarning: Skipping variable loading for optimizer 'rmsprop', because it has 4 variables whereas the saved optimizer has 2 variables. 
  saveable.load_own_variables(weights_store.get(inner_path))


In [52]:
new_model2.predict(np.array([5]))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 467ms/step


array([[10.025499]], dtype=float32)

In [6]:
#test_model
import numpy as np
import tensorflow.keras as k
model = k.models.load_model('my_model.h5')
x_test = np.array([6, 7, 8], dtype=float)
y_test = np.array([12, 14, 16], dtype=float)
loss = model.evaluate(x_test, y_test)
print('test-loss', loss)


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 325ms/step - loss: 1.4578e-04
test-loss 0.0001457775942981243
